### ISSUE TITLE
No declaration file

### ISSUE THREAD

**Issue by paul-uz** [kwojcicki/amazon-dax-client-v3#3]
I'm using this in a Typescript project, and TS complains that there is no declaration file. 

Any chance this can be added?

**Comment by kwojcicki** [comment]
Added some typings https://github.com/kwojcicki/amazon-dax-client-v3/blob/main/src/AmazonDaxClient.d.ts, they are pretty permissive, in comparison to what DAX can actually do, I'll prune it down later
