### ISSUE TITLE
missing properties

### ISSUE THREAD

**Issue by daveharig** [kwojcicki/amazon-dax-client-v3#6]
const daxClient = new AmazonDaxClient({
  _client_: DynamoDBDocumentClient.from(new DynamoDBClient({
    endpoint: daxEndpoint,
    region: Configs.REGION.MAIN
  }))
});

Error: Type 'DynamoDBDocumentClient' is missing the following properties from type 'DynamoDBClient': getDefaultHttpAuthSchemeParametersProvider, getIdentityProviderConfigProviderts(2739)
AmazonDaxClient.d.ts(8, 5): The expected type comes from property 'client' which is declared here on type '{ client: DynamoDBClient; config: { skipHostnameVerification?: boolean | undefined; maxRetries?: number | undefined; writeRetries?: number | undefined; readRetries?: number | undefined; ... 8 more ...; threadKeepAlive?: number | undefined; }; }'

**Comment by kwojcicki** [comment]
I have a code change locally that should fix this. I'll push it later tonight sorry about the inconvenience

**Comment by kwojcicki** [comment]
hey dave, this should be fixed in the latest 1.0.5 release as part of https://github.com/kwojcicki/amazon-dax-client-v3/commit/f4cfda7d9335578b67882e36264b67ea6139ae98#diff-1d303347dc4638b4f5afae892c1832c797f99c033d5ca672aaf69201f30880f6

**Comment by daveharig** [comment]
Bug squashed! Thank you!
